
#ifdef NT
//# define CONFIG_WIN32_USE_CRYPTO_LIB
#endif

//CONFIG_SSL_SERVER_ONLY 
//CONFIG_SSL_CERT_VERIFICATION 
#define CONFIG_SSL_ENABLE_CLIENT
//CONFIG_SSL_FULL_MODE
#define CONFIG_SSL_PROT_MEDIUM
#define CONFIG_SSL_USE_DEFAULT_KEY
#define CONFIG_SSL_PRIVATE_KEY_LOCATION ""
#define CONFIG_SSL_PRIVATE_KEY_PASSWORD ""
#define CONFIG_SSL_X509_CERT_LOCATION ""
//CONFIG_SSL_GENERATE_X509_CERT
//CONFIG_SSL_X509_COMMON_NAME=""
//CONFIG_SSL_X509_ORGANIZATION_NAME=""
//CONFIG_SSL_X509_ORGANIZATION_UNIT_NAME=""
//CONFIG_SSL_ENABLE_V23_HANDSHAKE
#define CONFIG_SSL_HAS_PEM
#define CONFIG_SSL_USE_PKCS12
#define CONFIG_SSL_EXPIRY_TIME 24
#define CONFIG_X509_MAX_CA_CERTS 4
#define CONFIG_SSL_MAX_CERTS 2
// CONFIG_SSL_CTX_MUTEXING
// CONFIG_USE_DEV_URANDOM
// CONFIG_OPENSSL_COMPATIBLE
// CONFIG_PERFORMANCE_TESTING
// CONFIG_SSL_TEST is not set

// CONFIG_BIGINT_CLASSICAL
// CONFIG_BIGINT_MONTGOMERY
#define CONFIG_BIGINT_BARRETT
#define CONFIG_BIGINT_CRT
// CONFIG_BIGINT_KARATSUBA is not set
#define MUL_KARATSUBA_THRESH 0
#define SQU_KARATSUBA_THRESH 0
#define CONFIG_BIGINT_SLIDING_WINDOW
#define CONFIG_BIGINT_SQUARE
// CONFIG_BIGINT_CHECK_ON

